### ISSUE TITLE
App Crash when press on buttonRow()

### ISSUE THREAD

**Issue by christianhr** [xmartlabs/Eureka#2017] opened 2020-03-31 06:28 UTC
My App crash when pressing on ButtonRow() method row.onCellSelection
I'm using latest version of xcode and iOS 13.4 and latest of Eureka
```

<<< ButtonRow(){ row in
                row.title = "Registrarse"
                row.onCellSelection { (cell, row) in
                      //APP CRASH HERE 
                    print("hola")
                }
```

**Comment by mats-claassen** [comment] 2020-03-31 12:26
This is a compiler issue. Fixed in Eureka 5.2.1

Duplicate of #2015, #2014, #2009, #1987, #1988, #1999

**Comment by christianhr** [comment] 2020-03-31 16:08
As I Said, I have the last versión of eureka (5.2.1), the crash is still happening please don't close this issue

**Comment by mats-claassen** [comment] 2020-04-01 12:47
Sorry if I misunderstood you. I just added your code to the Example project in Xcode 11.4, iOS 13.4, Eureka 5.2.1 and it works perfectly. 

When you post "latest" version of Eureka, that does not tell me which version you are actually using as you might not have seen a recent release. Also, if somebody comes back to see this issue in some time the "latest" version will be another one. So it is preferable to state the exact version you are using.

So, if you are sure that you are using version 5.2.1 then it would be great to have a stack trace / error message or something to work on

**Comment by mats-claassen** [comment] 2020-10-28 11:56
Closing due to lack of activity

**Closed by mats-claassen** 2020-10-28 11:56 UTC
Labels: duplicate
