### ISSUE TITLE
When click a TextAearRow , app crash  in Eureka 4.0.1

### ISSUE THREAD

**Issue by realcarlos** [xmartlabs/Eureka#1367] opened 2017-12-21 19:02 UTC
```swift
            +++ Section("Remark")
            <<< TextAreaRow() {
                $0.tag = "Remark"
                $0.textAreaHeight = .dynamic(initialTextViewHeight: 60)
                $0.value = result.remark
                }.cellSetup({ (cell, row) in
                    cell.textView.font = UIFont.systemFont(ofSize: 16)
                })
```

<img width="469" alt="2017-12-22 2 53 14" src="https://user-images.githubusercontent.com/13853/34270832-8ecf2da8-e6c4-11e7-8624-64c63b52ee99.png">

**Comment by m-revetria** [comment] 2018-01-08 15:02
Hi @realcarlos, I've tried the code you provided and cannot reproduce the error. Can you share all your form's configuration and let us know the steps to reproduce it?

**Comment by carlosbdw** [comment] 2018-01-10 08:30
Thanks m-ervetria , I know the reason ,I defined a veritable of Section ,and used it in two places. I will close this issue.

**Comment by m-revetria** [comment] 2018-01-10 19:35
Ok, cool. I'm closing the issue.

Thanks

**Closed by m-revetria** 2018-01-10 19:35 UTC
Labels: type: awaiting response
