### ISSUE TITLE
Dynamic text height for cell

### ISSUE THREAD

**Issue by iOSUser110** [xmartlabs/Eureka#960] opened 2017-03-14 11:18 UTC
That will be really great if you provide multiline support but dynamic in nature. So after this support library going to save lot of time of developers.
and also the button text color, button background color for buttonRow

**Comment by GoSwiftlyIntoThisGoodNight** [comment] 2017-03-14 19:13
I don't know about the multiline support (never had to use it), but you can change a button's text color by changing the tintcolor of the underlying cell. 
So: row.cell.tintColor = UIColor.red, for instance. It is the same for the background color.
row.cell.backgroundColor = UIColor.gray.

**Comment by santiagofm** [comment] 2017-05-23 16:14
Duplicate of #946

**Closed by santiagofm** 2017-05-23 16:14 UTC
