### ISSUE TITLE
Segmentation fault: 11 when building to simulator with Xcode 12

### ISSUE THREAD

**Issue by aPandeyisystango** [xmartlabs/Eureka#2068] opened 2020-08-26 12:12 UTC
When I build project on Xcode 12 I am getting error error: Segmentation fault: 11 (in target 'Eureka' from project 'Pods')
after updating version 5.2.1
![Screenshot 2020-08-26 at 5 41 45 PM](https://user-images.githubusercontent.com/67690419/91302052-7e30fc80-e7c3-11ea-9952-1a1298eab4db.png)

**Comment by kamerc** [comment] 2020-08-26 15:04
https://github.com/xmartlabs/Eureka/issues/2057

**Comment by mats-claassen** [comment] 2020-08-27 12:55
Closing as duplicate of #2057

**Closed by mats-claassen** 2020-08-27 12:55 UTC
