### ISSUE TITLE
PickerInLineRow not expanding on tap (Swift 4.2)

### ISSUE THREAD

**Issue by roddymunro** [xmartlabs/Eureka#1656] opened 2018-09-07 20:30 UTC
- Environment: Eureka 4.2, iOS 12 Beta 12, Xcode 10 Beta 6

I am using this code for my form, which has worked on previous Eureka/iOS versions. 

```swift
    form
            +++ Section("")
            <<< PickerInlineRow<String>("CountriesRow") { (row : PickerInlineRow<String>) -> Void in
                row.title = "Country"
                row.options = ["USA", "Canada"]
                row.value = row.options[0]
                row.add(rule: RuleRequired())
            }
            
            <<< PickerInlineRow<String>("StatesRow") { (row : PickerInlineRow<String>) -> Void in
                row.title = "State"
                row.options = ["Alabama", "Alaska"]
                row.value = row.options[0]
                row.add(rule: RuleRequired())
            }
```

When tapping on the two PickerInlineRows after building the app, the row doesn't expand as expected. The row remains highlighted, however I am unable to change the value:
![img_4304](https://user-images.githubusercontent.com/11502253/45241685-4209e600-b2e5-11e8-8a9b-189dc785e2b2.GIF)

**Comment by mats-claassen** [comment] 2018-09-10 13:51
Works for me with Xcode 10 beta 4. Is this something that appeared with beta 6? Are you sure you did not change other things in your code? For example, not calling `super` in some methods can have weird consequences

**Comment by mats-claassen** [comment] 2018-10-16 14:04
Closing as not reproducible

**Closed by mats-claassen** 2018-10-16 14:04 UTC

**Comment by roddymunro** [comment] 2018-10-21 10:56
This is fixed in 4.3.

**Comment by thejoaovitor** [comment] 2020-05-30 00:18
@mats-claassen I was able to reproduce this issue in the RowsExampleViewController. It happens when override func viewWillAppear is called without calling super at some point.

`override func viewWillAppear(_ animated: Bool) {
        //super.viewWillAppear(true)  //uncomment to fix

    }`

**Comment by thejoaovitor** [comment] 2020-05-30 00:23
@mats-claassen I was able to reproduce this issue in the RowsExampleViewController. It happens when viewWillAppear is used without calling super at some point.

```
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)  //Comment this line to reproduce
}
```
