### ISSUE TITLE
Scrolling cause cells disappearance 

### ISSUE THREAD

**Issue by annamusial** [xmartlabs/Eureka#936] opened 2017-02-20 15:25 UTC
- Environment: Eureka 2.0.1, Xcode 8.2.1, iOS 10
- Description: After filling some cells in my form and scrolling up (after keyboard is closed) the first few cells disappear. They appear again, after scrolling down and up.
![img_6940](https://cloud.githubusercontent.com/assets/22073026/23131126/2ff16e5c-f789-11e6-92f5-85cb2d6ddc5d.PNG)
![img_6941](https://cloud.githubusercontent.com/assets/22073026/23131127/3018bb2e-f789-11e6-8cf5-f4f385a19b19.PNG)

**Comment by mtnbarreto** [comment] 2017-02-20 18:44
Are these rows created by you, right?

**Comment by annamusial** [comment] 2017-02-20 21:43
Yes, those are custom Eureka rows

**Comment by timboettiger** [comment] 2017-03-13 17:06
I can verify this behavior with standard rows like TextRow, TextAreaRow and SwitchRow.

Initial view (Looks also not good - but why?):
<img width="373" alt="" src="https://cloud.githubusercontent.com/assets/26388324/23865928/8ca6af42-0817-11e7-9344-d1961e93a167.png">

After dragging form to top and letting it go:
<img width="378" alt="" src="https://cloud.githubusercontent.com/assets/26388324/23865896/6fa46114-0817-11e7-8719-7f49c026ed2a.png">

Build using the following code:
<img width="373" alt="" src="https://cloud.githubusercontent.com/assets/26388324/23865865/54d82212-0817-11e7-98a6-019cfe1587db.png">

**Comment by timboettiger** [comment] 2017-03-13 17:19
@annamusial Found the issue: I was using a TableViewController from the xcode object library within the storyboard. When I replaced it using a ViewController, everything works as expected.

@mtnbarreto Maybe you could extend the readme to prevent others making the same mistake?

**Comment by santiagofm** [comment] 2017-05-25 16:07
Hey @timboettiger ! 
I don't really see how you could have used a `UITableViewController` given that you have to inherit from `FormViewController` and it itself is a plain `UIViewController` with a `tableView` in it.

Anyway guys, please provide a sample project to reproduce the issue or steps to reproduce it with the Example project.

Cheers

**Comment by m-revetria** [comment] 2017-06-09 14:51
Closing this, seems to be resolved.
The readme says that to create a form you have to extend from `Eureka.FormViewController`, you can take a look to https://github.com/xmartlabs/Eureka#how-to-create-a-form. That would be enough I think.

Thanks

**Closed by m-revetria** 2017-06-09 14:51 UTC
Labels: type: awaiting response
