### ISSUE TITLE
Crash when invoke cellUpdate 

### ISSUE THREAD

**Issue by Gnoah89** [xmartlabs/Eureka#2042] opened 2020-05-27 01:54 UTC
Xcode  Version 11.4.1 (11E503a)
Eureka (5.2.0)

I simple write code as follow 

`
import UIKit
import Eureka

class InfoViewController: FormViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        self.navigationItem.title = "完善信息"
        self.tableView.separatorStyle = .singleLine
        self.tableView.separatorInset = UIEdgeInsets.zero

        form +++ Section()
            <<< LabelRow("Info") { row in
                row.title = "请输入正确信息以便我们提供售后服务"
                row.cellStyle = .default
                row.cell.height = { 60 }
            }.cellUpdate { (cell, row) in
                cell.textLabel?.textAlignment = .center
            }
            <<< PhoneRow("Phone") { row in
                row.cellStyle = .default
                row.cell.height = { 60 }
            }.cellUpdate { (cell, row) in
                cell.textField.placeholder = "请输入手机号"
                cell.textField.textAlignment = .center
                cell.textField.keyboardType = .numberPad
            }
     }
}
`

 It crash !

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gf6ru5a0xjj31fs0bwdic.jpg)

**Comment by mats-claassen** [comment] 2020-05-27 13:03
This is a duplicate of #1987 #1988 #1989 #1999 and others. Please review existing issues before posting new ones.

Updating to Eureka 5.2.1 should fix the issue

**Closed by mats-claassen** 2020-05-27 13:03 UTC

**Comment by Gnoah89** [comment] 2020-05-29 03:02
> This is a duplicate of #1987 #1988 #1989 #1999 and others. Please review existing issues before posting new ones.
> 
> Updating to Eureka 5.2.1 should fix the issue

NOT The same， I am not use beta iOS /Xcode

**Comment by mats-claassen** [comment] 2020-05-29 17:25
Have you tried upgrading to Eureka 5.2.1? Does it happen if you use that version?

**Comment by urm9ril** [comment] 2020-07-10 09:40
maybe you should change your xCode "WorkSpaces Settings"
