### ISSUE TITLE
warning xcode 11.3.1 

### ISSUE THREAD

**Issue by mimocu** [xmartlabs/Eureka#1986] opened 2020-02-06 21:02 UTC
this error appears in the xcode compiler:

Cast from 'BaseMultivaluedSection' to unrelated type 'GenericMultivaluedSection<AddButtonType>' always fails

**Comment by mats-claassen** [comment] 2020-02-17 12:25
Duplicate of #1982

**Closed by mats-claassen** 2020-02-17 12:25 UTC
