### ISSUE TITLE
Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

### ISSUE THREAD

**Issue by sagealessandra** [xmartlabs/Eureka#1568] opened 2018-06-05 13:43 UTC
I am using Eureka with Cocoapods on the latest version of Xcode and Swift. It will not build because of this error popping up, line 247 in Section.swift.

**Comment by mats-claassen** [comment] 2018-06-05 14:11
Duplicate of #1498 and others

**Closed by mats-claassen** 2018-06-05 14:11 UTC

**Comment by onvika** [comment] 2019-05-26 17:08
Hi, I am using swift 4.1 and Xcode 9.4.1
if I use Eureka '4.2' I get bunches of errors
if I use Eureka '4.0' I get this: Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

I have already tried this: pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift-3.3'

I have include this: post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == 'Eureka'
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '4.1'
end
end
end
end

I think I have read and tried almost all, and yet... I can not solve it ;/
any ideas ??
