### ISSUE TITLE
iOS 13 causes freeze on TextRow

### ISSUE THREAD

**Issue by GoldenJoe** [xmartlabs/Eureka#1920] opened 2019-10-01 00:30 UTC
When tapping a TextRow, or IntRow (and presumably other rows that open the keyboard), the app will freeze when running on simulator.

Xcode: 11.0 (11A420a)
Eureka: 5.0.1

**Comment by mats-claassen** [comment] 2019-10-02 12:23
Hi @GoldenJoe I could not reproduce this in the Examples. Are you sure it is not some of your code producing this? Otherwise could you provide a way to reproduce this?

**Comment by GoldenJoe** [comment] 2019-10-02 14:52
Certain it’s not my code. I think it was just a simulator bug.


________________________________

**Comment by bakeddean** [comment] 2019-10-14 03:13
Yeah, I can confirm this as well. Tapping directly in a TextRow, the keyboard does not come up, only the keyboard tool bar, which is anchored to the bottom of the screen, and the simulator freezes.

A DateRow works ok, but if you use the keyboard toolbar prev/next button to navigate to a TextRow / PhoneRow etc, the simulator freezes.

This is Eureka 5.1.0, Xcode 11.0 (11A420a)

**Comment by mats-claassen** [comment] 2019-11-04 14:35
Do you experience this issue only on a simulator or also a real device? That the keyboard deos not come up usually means that you have your hardware keyboard connected. You can then show the simulator keyboard with `Cmd+K`

**Comment by bakeddean** [comment] 2019-11-04 23:34
Yeah, the keyboard was a red herring. Thats ok, but still freezes on a TextRow. This is on the simulator, so hopefully just a simulator bug as @GoldenJoe says.

**Comment by bakeddean** [comment] 2019-11-04 23:47
Looks like this is nothing to do with Eureka.
https://forums.developer.apple.com/thread/122972

Deselect "Simulator -> Edit -> Automatically Sync Pasteboard", then
"Hardware -> Restart"

Fixed it.

**Comment by mats-claassen** [comment] 2019-11-05 12:01
OK, thanks for clarifying that. Will close this issue as not related to Eureka

**Closed by mats-claassen** 2019-11-05 12:01 UTC
