### ISSUE TITLE
Crash on deinit when adding NameRow or PasswordRow to a section

### ISSUE THREAD

**Issue by realenginerd** [xmartlabs/Eureka#828] opened 2016-12-06 23:55 UTC
I have a form that has, among other things, a name and a password field. When I close the FormViewController, I get a crash on FieldRow's deinit method. Here's my form creation code:

```swift
fileprivate func createForm(options: SVEncryptionOptions)
{
    form +++ fileSection()
    form +++ detailsSection(options: options)
    form +++ optionsSection(options: options)
}

fileprivate func detailsSection(options: SVEncryptionOptions) -> Section
{
    let section = Section("Details")
    section <<< NameRow()
    {
        $0.title = "Name"
        $0.tag = EncryptionViewController.tagRowName
    }

    let encryptionIsEnabled = options.encryptionState.contains(.on)
    let passwordIsAllowed = options.passwordState.contains(.on)
    if encryptionIsEnabled && passwordIsAllowed
    {
        section <<< PasswordRow()
        {
            $0.title = "Password"
            $0.tag = EncryptionViewController.tagRowPassword
        }
        section <<< PasswordRow()
        {
            $0.title = "Confirm Password"
            $0.tag = EncryptionViewController.tagRowConfirmPassword
        }
    }

    return section
}
```

(`SVEncryptionOptions` is an Obj-C class that provides details on whether to hide or display certain rows in the form.)

I'm not entirely sure what I am doing wrong (or not doing) to cause the crash. Some guidance would be appreciated. Thanks!

**Comment by mtnbarreto** [comment] 2016-12-07 17:00
Hi @realenginerd Please share the entire view controller and other associated files code so i  can reproduce the issue.

**Comment by realenginerd** [comment] 2016-12-07 19:27
@mtnbarreto Here's the view controller and another related class used in it: https://gist.github.com/realenginerd/ebd93055a059fcf9c6620dd0091ab935

The problem appears in line 157, in `archiveDetailsSection()`. When I append a `NameRow` or a `PushRow` into the section, I get a crash every time I close this view controller. I've used `NameRow` and `PushRow` in other parts of my app and I did not encounter this issue, so I'm not sure what is different that is causing this behavior.

**Comment by realenginerd** [comment] 2016-12-08 14:57
Not sure if this will help, so I'll include it anyway. The app crashes on the deinit method of `_FieldCell`, and I get the following output printed to my console:

```
2016-12-08 08:54:12.423597 Smartcrypt[1576:754147] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x16ef1ac0 of class UITableViewLabel was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x16e41300> (
<NSKeyValueObservance 0x16ef2440: Observer: 0x17ab6600, Key path: text, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x16ef2420>
)'
*** First throw call stack:
(0x1d7dee07 0x1ca3f077 0x1d7ded4d 0x1e07a621 0x1ca596eb 0x2290c609 0x10577b0 0x1057874 0x1d7d04ef 0x1d6f0587 0x1ca59195 0x22b713fb 0x1ca3e047 0x1ca48ec5 0x1ca48ee5 0x22bbdf4b 0x2282f1c9 0x2290cca3 0x229bf93d 0x1ca596eb 0x2282f1a7 0x1ca596eb 0x2282f1a7 0x1ca596eb 0x2282f1a7 0x229bf443 0x1ca596eb 0x2282f1a7 0x229bf3b3 0x1ca596eb 0x1d6e7df9 0x1d798d05 0x1d6e8073 0x1d6e7e81 0x1ee94bfd 0x2289c82f 0x22896f61 0x91b5b 0x1ceb250b)
libc++abi.dylib: terminating with uncaught exception of type NSException
Signal: SIGABRT (signal SIGABRT)
```

**Comment by realenginerd** [comment] 2016-12-08 19:25
I think I've discovered what the issue is. I put breakpoints everywhere `titleLabel` (in `_FieldCell`) is used in a KVO call. It turns out that every `NameRow` or `PasswordRow` is getting added to KVO twice, once during `setUp()` and once during `UIApplicationDidBecomeActive`, while only getting removed from KVO once, during `deinit`. Removing the second add caused the crash to disappear. 

My view controller gets presented when the app is invoked through another app's Open In menu. This explains the `UIApplicationDidBecomeActive` notification. 

While there is nothing inherently wrong with this behavior by `_FieldCell`, it does make it difficult for users trying to display a Form that has a `FieldCell` when coming back from an absence (which is admittedly corner case-y), as those forms might crash when they are dismissed. I fixed the issue by introducing a delay before displaying the Form. If there is a better way to fix this, I'd like to know.

@mtnbarreto anything else to add? Comments? My issue is resolved, so feel free to close.

**Comment by jiangyancong** [comment] 2017-01-06 05:23
@realenginerd I met totally the same issue with yours. Do u think it's a good design?Is it necessary to  removeObserver in UIApplicationWillResignActive and add it back in UIApplicationDidBecomeActive?

**Comment by kuquert** [comment] 2017-01-31 18:40
This [pull request](https://github.com/xmartlabs/Eureka/pull/884) solves this issue

**Comment by m-revetria** [comment] 2017-05-18 12:21
Closing this because it was solved in that PR

**Closed by m-revetria** 2017-05-18 12:21 UTC
Labels: type: awaiting response
