### ISSUE TITLE
Custom validation rule - Incorrect argument label in call (have 'rule:', expected 'ruleSet:')

### ISSUE THREAD

**Issue by marekpridal** [xmartlabs/Eureka#1625] opened 2018-07-31 12:45 UTC
Hi, I have a problem with own validation rule. I have created own rule for phone number validation and added it to row in form.
```swift
import Foundation
import Eureka

class RulePhoneNumber: RuleRegExp {

    init(msg: String, id: String? = nil) {
        super.init(regExpr: "^\\d{9}$", allowsEmpty: true, msg: msg, id: id)
    }

}
```

```swift
<<< OnboardingPhoneNumberRow(tag: OnboardingSetupInformationViewModel.RowIdentifier.phoneNumber.rawValue, canChangePrefix: false) {
    $0.add(rule: RuleRequired())
    $0.add(rule: RulePhoneNumber(msg: ""))
    $0.validationOptions = .validatesOnChange
}
```
but I'm getting comlication error `Incorrect argument label in call (have 'rule:', expected 'ruleSet:')`. I tried to add rules to ruleSet and then add it to row but it doesn't help either 😞

**Comment by mats-claassen** [comment] 2018-07-31 13:34
The error thrown by Xcode does not seem correct. I copied your code and it compiles in the example project.

There might possibly be an issue with your definition of `OnboardingPhoneNumberRow` or that `RulePhoneNumber ` is somehow not accessible.

**Comment by marekpridal** [comment] 2018-07-31 13:57
But my custom row works with generic rules...

```swift
final class OnboardingPhoneNumberRow: Row< OnboardingPhoneNumberCell>, RowType, KeyboardReturnHandler {
    var keyboardReturnType: KeyboardReturnTypeConfiguration?
    var canChangePrefix: Bool = true

    required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider< OnboardingPhoneNumberCell>(nibName: "OnboardingPhoneNumberCell")
    }

    required init(tag: String?, canChangePrefix: Bool = true, setupBlock: ((OnboardingPhoneNumberRow) -> Void)? = nil) {
        self.canChangePrefix = canChangePrefix
        super.init(tag: tag)
        cellProvider = CellProvider< OnboardingPhoneNumberCell>(nibName: "OnboardingPhoneNumberCell")

        setupBlock?(self)
    }
}
```

**Comment by mats-claassen** [comment] 2018-08-01 13:15
I don't know what the issue is but did you check that you can create a `RulePhoneNumber`?

Like, what is the error if you write:
```swift
let r = RulePhoneNumber(msg: "")
$0.add(rule: r)
```

**Comment by marekpridal** [comment] 2018-08-04 15:57
Sorry for the delay. Anyway I can construct rule object but when I try to add rule to row I get error ‘Incorrect argument label in call (have 'rule:', expected 'ruleSet:')’.

**Comment by jorgelub12** [comment] 2018-08-21 22:05
I'm trying to figure out someway to use as parameter.

**Comment by mats-claassen** [comment] 2018-08-22 12:05
Closing the issue as not reproducible

**Closed by mats-claassen** 2018-08-22 12:05 UTC
Labels: type: question
