### ISSUE TITLE
Update for Swift 4.2

### ISSUE THREAD

**Issue by yusuftor** [xmartlabs/Eureka#1662] opened 2018-09-18 09:41 UTC
I've just tried running my app using Xcode 10 and it's coming up with 100 errors due to not being updated for Swift 4.2. Please could someone update it?
Thanks!

**Comment by Kros-s** [comment] 2018-09-19 01:16
If i'm not wrong the PR for support for 4.2 is already merged

**Comment by piers12** [comment] 2018-09-19 09:28
Mixpanel, if you can't be bothered to update to Swift 4.2, then why should I bother using it when there are other forever free alternatives?

**Comment by mats-claassen** [comment] 2018-09-19 13:42
Duplicate of #1601. Version update is coming

**Comment by paulsUsername** [comment] 2018-09-21 11:21
How do you point to the master?

**Comment by mats-claassen** [comment] 2018-09-21 18:20
Version 4.3.0 released with  Swift 4.2 support 🎉

**Closed by mats-claassen** 2018-09-21 18:20 UTC

**Comment by sayoojkrishnan** [comment] 2018-09-22 16:47
How do i install version 4.3.0 ??
I'm getting version  4.2.0 with Cocoapods which has more than 100 issues.

**Comment by mats-claassen** [comment] 2018-09-24 14:51
What version did you specify in your Podfile? And are you running `pod update` or `pod install`?

**Comment by sayoojkrishnan** [comment] 2018-09-25 10:38
@mats-claassen pod update fixed my issues . Thanks

**Comment by ashish-naik** [comment] 2018-10-07 14:59
I upgraded to 4.3.0 but getting many errors. When i try to convert the project to 4.2, XCode doesn't go ahead and asks to convert all other frameworks to 4.2.

Tried removing Eureka and ran install but didn't work. 

Feel this is chicken and egg !!

How do I solve it?

Thanks
Ashish

**Comment by mats-claassen** [comment] 2018-10-08 14:21
Possibly you just need to tell Xcode to compile Eureka with Swift 4.2. Have a look at [this issue](https://github.com/xmartlabs/Eureka/issues/1667#issuecomment-424376610)
