### ISSUE TITLE
IOS 14 Beta - Time Picker Changed.

### ISSUE THREAD

**Issue by johnlietzke** [xmartlabs/Eureka#2052] opened 2020-06-24 01:48 UTC
IOS 14 Beta has changed the format of the Time Picker.  No longer does a picker populate.  It is an input dialog that comes up instead.  

I am unable to change the color of the text row.
<img width="372" alt="Screen Shot 2020-06-23 at 6 46 44 PM" src="https://user-images.githubusercontent.com/4194767/85487765-0e638300-b582-11ea-99cf-7ecf281246db.png">

Also, would it be possible to change the color of the dialog box?
<img width="302" alt="Screen Shot 2020-06-23 at 6 46 54 PM" src="https://user-images.githubusercontent.com/4194767/85487774-115e7380-b582-11ea-9978-2d8713fe4205.png">

**Comment by mats-claassen** [comment] 2020-06-24 13:05
I can confirm that it seems the `DateRow` type of rows don't work in iOS 14 beta. DateInlineRow or DatePickerRow works. Same for time and date+time pickers. Somehow the `inputView` is not shown

To continue using the wheels layout for the pickers you can use:
```swift
cell.datePicker.preferredDatePickerStyle = .wheels
```

I haven't taken a look yet into customizing the colors of the new compact picker.

**Comment by johnlietzke** [comment] 2020-06-24 15:32
Thanks for the quick reply. I will try that.

I do not have date pickers in my app. I use a calendar setup for that. 

But the new time input is kind of nice.  
  
Thanks,
John

**Comment by kamerc** [comment] 2020-08-25 20:02
@johnlietzke I know this doesn't help what you need since you were looking for TimeRow and not TimeInline row but I just submitted a [pull request](https://github.com/xmartlabs/Eureka/pull/2067) to fix the date & time inline rows so that they match the iOS native apps. The styles were not displaying correctly in iOS14.

**Comment by johnlietzke** [comment] 2020-08-25 20:16
Thanks Kate, in the past the developers have waited until the GM version to make changes.  I do like the new native date and time as it is smaller and easier to input.  What do you think?

**Comment by kamerc** [comment] 2020-08-26 15:38
@johnlietzke either way. With my changes there is still support for 13.4+ and less than 13.4 (the default still works, additional config not needed). It doesn't matter to me when it is merged in.

**Comment by mats-claassen** [comment] 2021-03-02 17:55
Support for this has been released

**Closed by mats-claassen** 2021-03-02 17:55 UTC
Labels: row: DateRows, type: issue
