### ISSUE TITLE
VideoRow

### ISSUE THREAD

**Issue by Smiller193** [xmartlabs/Eureka#1606] opened 2018-07-13 03:27 UTC
Has anyone made a video row?

**Comment by SebastianBO** [comment] 2018-10-02 12:59
Any update on this?

**Comment by Smiller193** [comment] 2018-10-02 18:08
i wish

**Comment by mats-claassen** [comment] 2018-10-03 13:44
Duplicate of #33.

Just as I mentioned there, you should be able to do this using [ImageRow](https://github.com/EurekaCommunity/ImageRow) by changing a few variables of its ImagePickerController. As with most of these rows, the layout of the row will probably be different for each project.

**Comment by mats-claassen** [comment] 2019-01-09 20:38
A [VideoRow](https://github.com/EurekaCommunity/VideoRow) is implemented in EurekaCommunity

**Closed by mats-claassen** 2019-01-09 20:38 UTC
Labels: Eureka Community, type: feature request
