### ISSUE TITLE
Add custom table cell to PushRow or PushRow to UIViewController

### ISSUE THREAD

**Issue by harpreetsingh309** [xmartlabs/Eureka#2126] opened 2020-12-18 01:52 UTC
Tried two way of pushing.

1. PushRow
>>  <<< PushRow<EntryDataType> {
                $0.options = ["First","Second"]
                $0.title = "Module"
                $0.selectorTitle = "Module"
                }.onPresent { from, to in
                    to.selectableRowSetup = { row in
                        row.cellProvider = CellProvider<EntryDataType>(nibName: "EntryDataTypeTableCell", bundle: Bundle.main)
                    }
            } 

 EntryDataTypeTableCell is just UITableViewCell type
What is the way to present .xib table cell to push row? Can we make a custom cell and can push row? I have 3 items in a cell (bg color, image and title) And getting error : Could not cast value of type 'EntryDataTypeTableCell'  to 'Eureka.ListCheckCell<EntryDataType>'.

IF I do it with ListCheckCell then getting error: this class is not key value coding-compliant for the key

2. OptionRow 
>><<< ModulePushRow("Module", { (push) in
                push.title = "Module"
                push.onPresent { (_, controller) in
                    controller.title = "Module"
                }
            })
final class ModulePushRow: OptionsRow<PushSelectorCell<EntryDataType>>, PresenterRowType, RowType { }

When I tried pushing to another view controller then table view in it coming "nil" and it crashes. Error: Unexpectedly found nil while implicitly unwrapping an Optional value.

Is there any particular way to present view controller or adding custom cell xib in PushRow?

**Comment by mats-claassen** [comment] 2020-12-21 12:56
I will close this as duplicate of #2120. Please follow the conversation there. 
`SelectorViewController` uses `ListCheckRow` so you need a custom row which does not depend on `SelectorViewController` (you could subclass `_SelectorViewController` if it is useful for your case). I recognize there is a lot of subclassing here which maybe could be done a bit easier

**Closed by mats-claassen** 2020-12-21 12:56 UTC
