### ISSUE TITLE
Scrolling bug still there...

### ISSUE THREAD

**Issue by 99xs** [xmartlabs/Eureka#342] opened 2016-03-18 17:56 UTC
Hi there,

There still seems to be an issue with the scroll (very similar to #224 ).
Look at this video too: https://youtu.be/0Y7GNbXe3LM

The code I'm using is this one:

    func createForm() {
    EmailRow.defaultCellUpdate = {cell,row in
        cell.preservesSuperviewLayoutMargins = false
        cell.separatorInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        cell.layoutMargins = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 8)
    }

    PasswordRow.defaultCellUpdate = {cell,row in
        cell.preservesSuperviewLayoutMargins = false
        cell.separatorInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 8)
    }

    form +++=

        Section("Sign In")

        <<< EmailRow("email") {
            $0.title = "Email:"
        }

        <<< PasswordRow("password") {
            $0.title = "Password:"
    }
}

**Comment by YSDC** [comment] 2016-05-02 07:59
Isn't it an issue with your layout constraint? did you try to put background color )in view, form, etc to see what is exactly happening?

**Comment by mtnbarreto** [comment] 2016-05-13 19:43
@99xs Could you please provide a project to easily reproduce the issue because i couldn't. 

Regards

**Comment by mtnbarreto** [comment] 2016-05-16 13:07
I will close this for now. Feel free to reopen it when you share the project to reproduce it.

**Closed by mtnbarreto** 2016-05-16 13:07 UTC
Labels: type: awaiting response

**Comment by mvorisis** [comment] 2017-03-16 11:33
#703 #
