### ISSUE TITLE
Setting hidden to true doesn't hide row

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/Eureka#307] opened 2016-03-03 05:45 UTC
When I set up my row, I can toggle it's visibility BUT when I later try to change the visibility, it does not work.

```
        var row:BaseRow

        row = TextRow() {
            $0.tag = "first"
            $0.title = "First:"
            $0.hidden = false
            }.cellSetup({ (cell, row) -> () in
                cell.textField.autocorrectionType = .No
            })
        section <<< row
```

then in another method:

```
        self.form.rowByTag("first")!.hidden = true  // This should hide the row but it doesn't.
```

I am using 1.3.1 via CocoaPods.

**Comment by rlaferla** [comment] 2016-03-03 18:44
The tags do match. e.g.  first = first.  There was a typo in my example which I just corrected.

**Comment by rlaferla** [comment] 2016-03-03 19:18
I also updated to 1.4.1 and it still doesn't work.

**Comment by rlaferla** [comment] 2016-03-03 19:32
I created a test project to show this issue.  This is definitely a bug or a misunderstanding of how to hide rows:

```
import UIKit
import Eureka

class ViewController: FormViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        var section:Section
        var row:BaseRow

        
        // Do any additional setup after loading the view, typically from a nib.
        section = Section("Section")

        form +++ section
        
        row = TextRow() {
            $0.tag = "first"
            $0.title = "First Name:"
            }.cellSetup({ (cell, row) -> () in
                cell.textField.autocorrectionType = .No
            })
        section <<< row

        form.rowByTag("first")?.hidden = true
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}
```

**Comment by rlaferla** [comment] 2016-03-03 21:06
It works IF I change the code to:

```
row.hidden = true
row.evaluateHidden()
```

I don't see any information in the documentation that says that evaluateHidden() needs to be called.

**Comment by rlaferla** [comment] 2016-03-03 21:27
Also, even though my bug workaround hides the rows, the height of the tableview does not shrink.  When hiding rows, I need the table view to adjust it's size so that other views onscreen can claim that space.  I tried calling sizeToFit() and setting the tableview frame to contentSize.height but neither worked.

**Comment by mtnbarreto** [comment] 2016-03-05 00:39
@rlaferla Here you have the documentation for the `evaluateHidden()`: https://github.com/xmartlabs/Eureka#row-does-not-update-after-changing-hidden-or-disabled-condition , it's within FAQ readme section. 

In regards of the table view height issue, whenever you hide a row, the row is completely removed from the table view so I don't think changing the row height is a good approach. 

If you want to change the table view height i suggest you to use interface builder to create the view controller adding corresponding "height" constraint and updating its constant accordingly when rows are removed. 

Take into account that rows are removed with animation so it may take some time to get the proper tableView contentSize value. 

I'm gonna close the issue since for now since It's seems not directly related with eureka. 
I'm willing to provide morehelp in case you share a project reproducing the issue.

**Closed by mtnbarreto** 2016-03-05 00:39 UTC

**Comment by rlaferla** [comment] 2016-03-05 01:40
I think this should be mentioned in the readme under the section: "How to dynamically hide and show rows (or sections)"  It's not obvious.

**Comment by johnpaulmanoza** [comment] 2017-03-10 03:44
Got stucked with the same issue. Can we make it obvious to the documentation?

**Comment by wsimf** [comment] 2017-09-27 03:54
I think this should also be clearly mentioned in the main documentation. I might not be the only one getting stuck with this same issue.

**Comment by simonbromberg** [comment] 2018-01-02 21:00
I am experiencing a similar issue with a MultivaluedSection where I am trying to hide the add button in the `multivaluedRowToInsertAt` block and I am calling `evaluateHidden` but it only hides the row when the 6th row is added (no matter what condition I check).

**Comment by rrodrigosa** [comment] 2022-01-29 01:47
> Got stucked with the same issue. Can we make it obvious to the documentation?

> I think this should also be clearly mentioned in the main documentation. I might not be the only one getting stuck with this same issue.

I got stuck with the same problem. Maybe it would indeed be nice to put in the main part of the documentation.
