### ISSUE TITLE
Picker Inline Row does not expand on click - Using Xcode 10 Swift 4

### ISSUE THREAD

**Issue by minon250** [xmartlabs/Eureka#1693] opened 2018-10-19 05:59 UTC
form +++ Section("Your names")
            <<< TextRow(){ row in
                row.title = "Screen Name"
                row.placeholder = "Your screen name"
            }

            <<< TextRow(){ row in
                row.title = "Full Name"
                row.placeholder = "Your full name"
            }

            +++ Section("Contact Information")
            <<< TextRow(){ row in
                row.title = "Email"
                row.placeholder = "E-mail address"
            }
            
            <<< PickerInlineRow<String>() {
                $0.title = "Country"
                //$0.selectorTitle = "Pick a number"
                $0.options = allCountries
                //$0.value = $0.options![0]    // initially selected
            }

**Comment by mats-claassen** [comment] 2018-10-23 12:18
Hi @minon250 I tried your code and it works in version 4.3. 
Closing as duplicate of #1656

**Closed by mats-claassen** 2018-10-23 12:18 UTC

**Comment by minon250** [comment] 2018-11-07 07:00
@mats-claassen could you please tell me what you are referring to when you say 4.3?

**Comment by melloskitten** [comment] 2019-11-11 10:45
For anyone experiencing the same problem, make sure to check whether you are appropriately calling the super methods in `viewWillAppear_ animated: Bool)`and `viewWillDisappear(_ animated: Bool)`. For me, not calling the supers resulted either in an out of bounds crash or the cell not doing anything at all, similarly to issue #1656.
