### ISSUE TITLE
header.onSetupView called multiple times

### ISSUE THREAD

**Issue by thierrybucco** [xmartlabs/Eureka#989] opened 2017-04-07 15:29 UTC
Hi,

In my project I am creating a custom section from a xib.

```swift
import UIKit
import Eureka

class ViewController: FormViewController {

	override func viewDidLoad() {
		super.viewDidLoad()
		addSection1()
	}

	private func addSection1() {
		let informationsSection = makeSectionView(title: "SECTION1")
		self.form +++ informationsSection
	}

	private func makeSectionView(title: String) -> Section {

		return Section() { section in
			var header = HeaderFooterView<CustomSectionView>(.nibFile(name: "CustomSectionView", bundle: nil))

			header.onSetupView = { view, _ in
				view.backgroundColor = UIColor.groupTableViewBackground
				view.titleLabel.text = title
				print("onSetupView")
			}
			section.header = header
		}
	}
}
```

I discovered that onSetupView is called each time view is being displayed .
For what I understand, onSetupView should be called once at creation time.

/// Closure called when the view is created. Useful to customize its appearance.

Do you have an idea?

Here is link to test project: https://www.dropbox.com/s/oiq1sn87l8r2gsq/onSetupViewTest.zip?dl=0

Thanks!

**Comment by thierrybucco** [comment] 2017-04-11 20:23
After investigation it seems that onSetupView should be called after createView and not at the end.
What do you think?

```
public func viewForSection(_ section: Section, type: HeaderFooterType) -> UIView? {
        var view: ViewType?
        if type == .header {
            view = section.headerView as? ViewType ?? {
                            let result = viewProvider?.createView()
                            section.headerView = result
				onSetupView?(result!, section)
                            return result
                        }()
        }
        else {
            view = section.footerView as? ViewType ?? {
                            let result = viewProvider?.createView()
                            section.footerView = result
				onSetupView?(result!, section)
                            return result
                        }()
        }
        guard let v = view else { return nil }
        //onSetupView?(v, section)
        return v
    }
```

**Comment by thierrybucco** [comment] 2017-04-18 13:59
@mats-claassen could you investigate this ticket and maybe accept my pull request? 
Thanks a lot.

**Comment by santiagofm** [comment] 2017-05-25 14:46
Hey @thierrybucco ! This seems like an issue to me. Would you mind updating the PR ?
Cheers

**Comment by thierrybucco** [comment] 2017-05-29 14:21
Hello @santiagofm I updated PR I hope all is ok.
Have a nice day.

**Comment by m-revetria** [comment] 2017-07-27 01:07
I'm closing this as it is by design.

**Closed by m-revetria** 2017-07-27 01:07 UTC
Labels: type: awaiting response

**Comment by thierrybucco** [comment] 2017-07-27 15:25
Hello, what is the best way to customize view only one time when created?
