### ISSUE TITLE
is it possible to implement expand collapse section 

### ISSUE THREAD

**Issue by sarrathy** [xmartlabs/Eureka#1836] opened 2019-05-16 02:42 UTC
I have to implement a expand and collapse section which has many textfield in that section . i need to have multiple section like that . Is it possible to do that  . Can you give me a example for it

**Comment by mats-claassen** [comment] 2019-05-30 12:53
Please search for similar issues before posting new ones. Duplicate of #1577 #1555 #477 #1031

**Closed by mats-claassen** 2019-05-30 12:53 UTC
