### ISSUE TITLE
Section: Index out of bounds

### ISSUE THREAD

**Issue by alexsanderkhitev** [xmartlabs/Eureka#918] opened 2017-02-04 18:11 UTC
Hello! I'm successful I needed a cell in multiple controllers, but in one of the controllers, I get an error Section: Index out of bounds, which will bring me into Section extension to this method

```swift
  public subscript (position: Int) -> BaseRow {
        get {
            if position >= kvoWrapper.rows.count{
                assertionFailure("Section: Index out of bounds") // crush
            }
            return kvoWrapper.rows[position] as! BaseRow
        }
        set { kvoWrapper.rows[position] = newValue }
    }
```

I did check on the correctness of the hiding cell index, the index I have the right.

How can I fix it?

**Comment by m-revetria** [comment] 2017-05-26 00:06
Hi @alexsanderkhitev, how are you sharing the row among the multiple view controllers?

Given the shared code we cannot help you so much. I cannot even know if the error is being thrown in either the getter or the setter block. Please provide us with a sample project where we can reproduce the issue in order to get further assistance.

**Comment by m-revetria** [comment] 2017-05-26 00:08
Recently we merged this PR #1028  that solves an issue in the way rows and sections are inserted to the form using subscripts. Maybe this is related, please try with the latest Eureka version to see if the issue is solved.

**Comment by m-revetria** [comment] 2017-06-09 14:53
Closing this due to lack of response

**Closed by m-revetria** 2017-06-09 14:53 UTC
Labels: type: awaiting response

**Comment by alexsanderkhitev** [comment] 2017-06-10 05:10
Hi @m-revetria  Sorry for the late reply, yes it solved my problem!
