### ISSUE TITLE
Section with attributed String and dynamic height 

### ISSUE THREAD

**Issue by iOSUser110** [xmartlabs/Eureka#959] opened 2017-03-14 11:00 UTC
Custom section is possible with xib file..but how to make it dynamic in nature. I want to add String of number of lines.

I can do this by simply adding section with string but cant change the text color and alignment.

waiting for reply.

**Comment by santiagofm** [comment] 2017-05-23 16:14
Duplicate of #960 & #946

**Closed by santiagofm** 2017-05-23 16:14 UTC
