### ISSUE TITLE
SwipeAction not working in iOS 10

### ISSUE THREAD

**Issue by allaire** [xmartlabs/Eureka#1457] opened 2018-03-15 18:37 UTC
Can be easily reproduced using a 10.3.1 simulator with the example app (in my case I'm using an iPad 5th gen 10.3.1).

If you try to tap the destructive button (or the more), nothing happens.

Current workaround I do is:

```swift
    if #available(iOS 11, *) {
    } else {
        if let section = self?.form.sectionBy(tag: "membersSection"), let indexPath = row.indexPath {
            section.remove(at: indexPath.row)
        }
    }
    
    completionHandler?(true)
```

**Comment by arakweker** [comment] 2018-03-15 18:39
Swipe actions are new in iOS 11...

**Comment by allaire** [comment] 2018-03-15 18:41
@arakweker I'm talking about the SwipeActions file in Eureka (https://github.com/xmartlabs/Eureka/blob/1ac7c98793ee1fdaae204fb87c9ea8f0001b8ef9/Source/Core/SwipeActions.swift). See in the README https://github.com/xmartlabs/Eureka#swipe-actions

**Comment by arakweker** [comment] 2018-03-15 18:44
Yep... look at that page... scroll down...

@available(iOS 11.0, *)
extension UIContextualAction: ContextualAction {}

public protocol ContextualStyle{}
extension UITableViewRowActionStyle: ContextualStyle {}

@available(iOS 11.0, *)
extension UIContextualAction.Style: ContextualStyle {}

**Comment by arakweker** [comment] 2018-03-15 18:45
Looks like they are extensions to the swipeactions in iOS 11

**Comment by allaire** [comment] 2018-03-15 18:46
@arakweker The class has support for pre iOS 11 using `UITableViewRowAction` which is available since iOS 8.

**Comment by mtnbarreto** [comment] 2018-03-23 21:11
@marbetschar Do you have time to look at it?

**Comment by marbetschar** [comment] 2018-03-24 08:54
@allaire unfortunately I can't reproduce the falsy behaviour on my end. I just checked out `master` and ran the iOS Simulator 10.3.1. I can see the expected print statements in the console.

FWIW: As you can see in the Example app, you as a developer are responsible for calling the passed in completionHandler (if there is any available):

```
let deleteAction = SwipeAction(style: .destructive, title: "Delete") { (action, row, completionHandler) in
    print("Delete")
    completionHandler?(true)
}
```

This is expected and due to the design how `UIContextualAction` is working from iOS 11 onwards.

**Comment by marbetschar** [comment] 2018-03-24 09:02
@allaire doh! Now I got what you mean, it really seems like the completionHandler of the underlying RowAction does not get called and therefore the buttons are not closed.

Investigating...

**Comment by marbetschar** [comment] 2018-03-24 09:53
Pull request added to handle the animations for iOS <= 10 in the completionHandler, so they behave like iOS >= 11.

https://github.com/xmartlabs/Eureka/pull/1477

**Comment by marbetschar** [comment] 2018-03-24 09:54
@mtnbarreto can you please have a look so we can get this merged?
@allaire thanks for pointing this out!

**Closed** 2018-03-26 19:03 UTC

**Comment by allaire** [comment] 2018-03-26 19:06
Yay thanks @marbetschar sorry if I wasn't clear with the issue in my first post :)

**Comment by mtnbarreto** [comment] 2018-03-26 19:14
@marbetschar Thanks for fixing it!!
